buildVariable: false
familyName: Noto Sans Math
googleFonts: true
includeSubsets:
- from: Noto Sans
  ranges:
      - start: 0x00A2
        end: 0x00A3
      - start: 0x00A5
        end: 0x00A5
      - start: 0x00A9
        end: 0x00A9
      - start: 0x00AE
        end: 0x00AE
      - start: 0x00B0
        end: 0x00B0
      - start: 0x00B7
        end: 0x00B7
      - start: 0x00C5
        end: 0x00C5
      - start: 0x00C7
        end: 0x00C7
      - start: 0x00D0
        end: 0x00D0
      - start: 0x00DE
        end: 0x00DE
      - start: 0x00E5
        end: 0x00E5
      - start: 0x00E7
        end: 0x00E7
      - start: 0x00F0
        end: 0x00F0
      - start: 0x00FE
        end: 0x00FE
      - start: 0x02C6
        end: 0x02C6
      - start: 0x0410
        end: 0x044F
      - start: 0x2021
        end: 0x2021
      - start: 0x20AC
        end: 0x20AC
      - start: 0x2118
        end: 0x2118
      - start: 0x2127
        end: 0x2127
sources:
  - NotoSansMath.glyphspackage
glyphData:
  - GlyphData.xml
